[package]
name = "creator_platform"
edition = "2024.beta"

[dependencies]
asset = { local = "../dependencies/asset" }
WAL = { local = "../dependencies/wal" }
Walrus = { local = "../dependencies/walrus" }

[addresses]
creator_platform = "0x0"
